[package]
name = "literals-and-operators"
version = "0.1.0"
authors = ["Andrei Olar <andrei.olar@samlex.ro>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
